hello_world: hello_world.cpp compile
	g++ ../../build/SGPLed.o hello_world.cpp -o ../../bin/hello_world -I ../;
	./../../bin/hello_world

compile: ../SGPLed.cpp
	g++ -c ../SGPLed.cpp -o ../../build/SGPLed.o -I ../
